<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="P11-AS-BX6QQ12" name="com.altisource.MPT_RefinanceTest.MptRefinanceTests" tests="34" failures="34" timestamp="30 Jul 2018 11:54:08 GMT" time="927.021" errors="0">
  <testcase name="runMptRefinanceTitleNEscrowTest" time="23.567" classname="com.altisource.MPT_RefinanceTest.MptRefinanceTests">
    <failure type="org.json.JSONException" message="JSONObject[&quot;TotalResultsCount&quot;] not found.">
      <![CDATA[org.json.JSONException: JSONObject["TotalResultsCount"] not found.
	at org.json.JSONObject.get(JSONObject.java:498)
	at com.data.altisource.library.MptRefinanceTestLibrary.getAllFileCount(MptRefinanceTestLibrary.java:335)
	at com.data.altisource.library.MptRefinanceTestLibrary.refinanceAllDataInsertQueries(MptRefinanceTestLibrary.java:70)
	at com.data.altisource.library.MptRefinanceTestLibrary.refinanceAllDataCreation(MptRefinanceTestLibrary.java:202)
	at com.altisource.MPT_RefinanceTest.MptRefinanceTests.runMptRefinanceTitleNEscrowTest(MptRefinanceTests.java:38)
	at sun.reflect.GeneratedMethodAccessor137.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:715)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:907)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1237)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:51)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:85)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1197)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1122)
	at org.testng.TestNG.run(TestNG.java:1030)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- runMptRefinanceTitleNEscrowTest -->
  <testcase name="runMptRefinanceTitleNEscrowTest" time="27.543" classname="com.altisource.MPT_RefinanceTest.MptRefinanceTests">
    <failure type="org.json.JSONException" message="JSONObject[&quot;TotalResultsCount&quot;] not found.">
      <![CDATA[org.json.JSONException: JSONObject["TotalResultsCount"] not found.
	at org.json.JSONObject.get(JSONObject.java:498)
	at com.data.altisource.library.MptRefinanceTestLibrary.getAllFileCount(MptRefinanceTestLibrary.java:335)
	at com.data.altisource.library.MptRefinanceTestLibrary.refinanceAllDataInsertQueries(MptRefinanceTestLibrary.java:70)
	at com.data.altisource.library.MptRefinanceTestLibrary.refinanceAllDataCreation(MptRefinanceTestLibrary.java:202)
	at com.altisource.MPT_RefinanceTest.MptRefinanceTests.runMptRefinanceTitleNEscrowTest(MptRefinanceTests.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:715)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:907)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1237)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:51)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:85)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1197)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1122)
	at org.testng.TestNG.run(TestNG.java:1030)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- runMptRefinanceTitleNEscrowTest -->
  <testcase name="runMptRefinanceTitleNEscrowTest" time="31.776" classname="com.altisource.MPT_RefinanceTest.MptRefinanceTests">
    <failure type="org.json.JSONException" message="JSONObject[&quot;TotalResultsCount&quot;] not found.">
      <![CDATA[org.json.JSONException: JSONObject["TotalResultsCount"] not found.
	at org.json.JSONObject.get(JSONObject.java:498)
	at com.data.altisource.library.MptRefinanceTestLibrary.getAllFileCount(MptRefinanceTestLibrary.java:335)
	at com.data.altisource.library.MptRefinanceTestLibrary.refinanceAllDataInsertQueries(MptRefinanceTestLibrary.java:70)
	at com.data.altisource.library.MptRefinanceTestLibrary.refinanceAllDataCreation(MptRefinanceTestLibrary.java:202)
	at com.altisource.MPT_RefinanceTest.MptRefinanceTests.runMptRefinanceTitleNEscrowTest(MptRefinanceTests.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:715)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:907)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1237)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:51)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:85)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1197)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1122)
	at org.testng.TestNG.run(TestNG.java:1030)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- runMptRefinanceTitleNEscrowTest -->
  <testcase name="runMptRefinanceTitleNEscrowTest" time="23.303" classname="com.altisource.MPT_RefinanceTest.MptRefinanceTests">
    <failure type="org.json.JSONException" message="JSONObject[&quot;TotalResultsCount&quot;] not found.">
      <![CDATA[org.json.JSONException: JSONObject["TotalResultsCount"] not found.
	at org.json.JSONObject.get(JSONObject.java:498)
	at com.data.altisource.library.MptRefinanceTestLibrary.getAllFileCount(MptRefinanceTestLibrary.java:335)
	at com.data.altisource.library.MptRefinanceTestLibrary.refinanceAllDataInsertQueries(MptRefinanceTestLibrary.java:70)
	at com.data.altisource.library.MptRefinanceTestLibrary.refinanceAllDataCreation(MptRefinanceTestLibrary.java:202)
	at com.altisource.MPT_RefinanceTest.MptRefinanceTests.runMptRefinanceTitleNEscrowTest(MptRefinanceTests.java:38)
	at sun.reflect.GeneratedMethodAccessor137.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:715)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:907)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1237)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:51)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:85)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1197)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1122)
	at org.testng.TestNG.run(TestNG.java:1030)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- runMptRefinanceTitleNEscrowTest -->
  <testcase name="runMptRefinanceTitleNEscrowTest" time="31.381" classname="com.altisource.MPT_RefinanceTest.MptRefinanceTests">
    <failure type="org.json.JSONException" message="JSONObject[&quot;TotalResultsCount&quot;] not found.">
      <![CDATA[org.json.JSONException: JSONObject["TotalResultsCount"] not found.
	at org.json.JSONObject.get(JSONObject.java:498)
	at com.data.altisource.library.MptRefinanceTestLibrary.getAllFileCount(MptRefinanceTestLibrary.java:335)
	at com.data.altisource.library.MptRefinanceTestLibrary.refinanceAllDataInsertQueries(MptRefinanceTestLibrary.java:70)
	at com.data.altisource.library.MptRefinanceTestLibrary.refinanceAllDataCreation(MptRefinanceTestLibrary.java:202)
	at com.altisource.MPT_RefinanceTest.MptRefinanceTests.runMptRefinanceTitleNEscrowTest(MptRefinanceTests.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:715)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:907)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1237)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:51)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:85)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1197)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1122)
	at org.testng.TestNG.run(TestNG.java:1030)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- runMptRefinanceTitleNEscrowTest -->
  <testcase name="runMptRefinanceTitleNEscrowTest" time="41.397" classname="com.altisource.MPT_RefinanceTest.MptRefinanceTests">
    <failure type="org.json.JSONException" message="JSONObject[&quot;TotalResultsCount&quot;] not found.">
      <![CDATA[org.json.JSONException: JSONObject["TotalResultsCount"] not found.
	at org.json.JSONObject.get(JSONObject.java:498)
	at com.data.altisource.library.MptRefinanceTestLibrary.getAllFileCount(MptRefinanceTestLibrary.java:335)
	at com.data.altisource.library.MptRefinanceTestLibrary.refinanceAllDataInsertQueries(MptRefinanceTestLibrary.java:70)
	at com.data.altisource.library.MptRefinanceTestLibrary.refinanceAllDataCreation(MptRefinanceTestLibrary.java:202)
	at com.altisource.MPT_RefinanceTest.MptRefinanceTests.runMptRefinanceTitleNEscrowTest(MptRefinanceTests.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:715)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:907)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1237)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:51)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:85)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1197)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1122)
	at org.testng.TestNG.run(TestNG.java:1030)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- runMptRefinanceTitleNEscrowTest -->
  <testcase name="runMptRefinanceTitleNEscrowTest" time="20.064" classname="com.altisource.MPT_RefinanceTest.MptRefinanceTests">
    <failure type="java.lang.NumberFormatException" message="For input string: &quot;&quot;">
      <![CDATA[java.lang.NumberFormatException: For input string: ""
	at java.lang.NumberFormatException.forInputString(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at com.data.altisource.library.MptRefinanceTestLibrary.refinanceAllDataInsertQueries(MptRefinanceTestLibrary.java:65)
	at com.data.altisource.library.MptRefinanceTestLibrary.refinanceAllDataCreation(MptRefinanceTestLibrary.java:202)
	at com.altisource.MPT_RefinanceTest.MptRefinanceTests.runMptRefinanceTitleNEscrowTest(MptRefinanceTests.java:38)
	at sun.reflect.GeneratedMethodAccessor137.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:715)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:907)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1237)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:51)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:85)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1197)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1122)
	at org.testng.TestNG.run(TestNG.java:1030)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- runMptRefinanceTitleNEscrowTest -->
  <testcase name="runMptRefinanceTitleNEscrowTest" time="23.768" classname="com.altisource.MPT_RefinanceTest.MptRefinanceTests">
    <failure type="org.json.JSONException" message="JSONObject[&quot;TotalResultsCount&quot;] not found.">
      <![CDATA[org.json.JSONException: JSONObject["TotalResultsCount"] not found.
	at org.json.JSONObject.get(JSONObject.java:498)
	at com.data.altisource.library.MptRefinanceTestLibrary.getAllFileCount(MptRefinanceTestLibrary.java:335)
	at com.data.altisource.library.MptRefinanceTestLibrary.refinanceAllDataInsertQueries(MptRefinanceTestLibrary.java:70)
	at com.data.altisource.library.MptRefinanceTestLibrary.refinanceAllDataCreation(MptRefinanceTestLibrary.java:202)
	at com.altisource.MPT_RefinanceTest.MptRefinanceTests.runMptRefinanceTitleNEscrowTest(MptRefinanceTests.java:38)
	at sun.reflect.GeneratedMethodAccessor137.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:715)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:907)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1237)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:51)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:85)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1197)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1122)
	at org.testng.TestNG.run(TestNG.java:1030)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- runMptRefinanceTitleNEscrowTest -->
  <testcase name="runMptRefinanceTitleNEscrowTest" time="29.822" classname="com.altisource.MPT_RefinanceTest.MptRefinanceTests">
    <failure type="org.json.JSONException" message="JSONObject[&quot;TotalResultsCount&quot;] not found.">
      <![CDATA[org.json.JSONException: JSONObject["TotalResultsCount"] not found.
	at org.json.JSONObject.get(JSONObject.java:498)
	at com.data.altisource.library.MptRefinanceTestLibrary.getAllFileCount(MptRefinanceTestLibrary.java:335)
	at com.data.altisource.library.MptRefinanceTestLibrary.refinanceAllDataInsertQueries(MptRefinanceTestLibrary.java:70)
	at com.data.altisource.library.MptRefinanceTestLibrary.refinanceAllDataCreation(MptRefinanceTestLibrary.java:202)
	at com.altisource.MPT_RefinanceTest.MptRefinanceTests.runMptRefinanceTitleNEscrowTest(MptRefinanceTests.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:715)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:907)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1237)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:51)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:85)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1197)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1122)
	at org.testng.TestNG.run(TestNG.java:1030)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- runMptRefinanceTitleNEscrowTest -->
  <testcase name="runMptRefinanceTitleNEscrowTest" time="29.554" classname="com.altisource.MPT_RefinanceTest.MptRefinanceTests">
    <failure type="org.json.JSONException" message="JSONObject[&quot;TotalResultsCount&quot;] not found.">
      <![CDATA[org.json.JSONException: JSONObject["TotalResultsCount"] not found.
	at org.json.JSONObject.get(JSONObject.java:498)
	at com.data.altisource.library.MptRefinanceTestLibrary.getAllFileCount(MptRefinanceTestLibrary.java:335)
	at com.data.altisource.library.MptRefinanceTestLibrary.refinanceAllDataInsertQueries(MptRefinanceTestLibrary.java:70)
	at com.data.altisource.library.MptRefinanceTestLibrary.refinanceAllDataCreation(MptRefinanceTestLibrary.java:202)
	at com.altisource.MPT_RefinanceTest.MptRefinanceTests.runMptRefinanceTitleNEscrowTest(MptRefinanceTests.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:715)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:907)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1237)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:51)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:85)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1197)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1122)
	at org.testng.TestNG.run(TestNG.java:1030)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- runMptRefinanceTitleNEscrowTest -->
  <testcase name="runMptRefinanceTitleNEscrowTest" time="23.362" classname="com.altisource.MPT_RefinanceTest.MptRefinanceTests">
    <failure type="org.json.JSONException" message="JSONObject[&quot;TotalResultsCount&quot;] not found.">
      <![CDATA[org.json.JSONException: JSONObject["TotalResultsCount"] not found.
	at org.json.JSONObject.get(JSONObject.java:498)
	at com.data.altisource.library.MptRefinanceTestLibrary.getAllFileCount(MptRefinanceTestLibrary.java:335)
	at com.data.altisource.library.MptRefinanceTestLibrary.refinanceAllDataInsertQueries(MptRefinanceTestLibrary.java:70)
	at com.data.altisource.library.MptRefinanceTestLibrary.refinanceAllDataCreation(MptRefinanceTestLibrary.java:202)
	at com.altisource.MPT_RefinanceTest.MptRefinanceTests.runMptRefinanceTitleNEscrowTest(MptRefinanceTests.java:38)
	at sun.reflect.GeneratedMethodAccessor137.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:715)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:907)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1237)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:51)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:85)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1197)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1122)
	at org.testng.TestNG.run(TestNG.java:1030)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- runMptRefinanceTitleNEscrowTest -->
  <testcase name="runMptRefinanceTitleNEscrowTest" time="23.839" classname="com.altisource.MPT_RefinanceTest.MptRefinanceTests">
    <failure type="org.json.JSONException" message="JSONObject[&quot;TotalResultsCount&quot;] not found.">
      <![CDATA[org.json.JSONException: JSONObject["TotalResultsCount"] not found.
	at org.json.JSONObject.get(JSONObject.java:498)
	at com.data.altisource.library.MptRefinanceTestLibrary.getAllFileCount(MptRefinanceTestLibrary.java:335)
	at com.data.altisource.library.MptRefinanceTestLibrary.refinanceAllDataInsertQueries(MptRefinanceTestLibrary.java:70)
	at com.data.altisource.library.MptRefinanceTestLibrary.refinanceAllDataCreation(MptRefinanceTestLibrary.java:202)
	at com.altisource.MPT_RefinanceTest.MptRefinanceTests.runMptRefinanceTitleNEscrowTest(MptRefinanceTests.java:38)
	at sun.reflect.GeneratedMethodAccessor137.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:715)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:907)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1237)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:51)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:85)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1197)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1122)
	at org.testng.TestNG.run(TestNG.java:1030)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- runMptRefinanceTitleNEscrowTest -->
  <testcase name="runMptRefinanceTitleNEscrowTest" time="27.076" classname="com.altisource.MPT_RefinanceTest.MptRefinanceTests">
    <failure type="org.json.JSONException" message="JSONObject[&quot;TotalResultsCount&quot;] not found.">
      <![CDATA[org.json.JSONException: JSONObject["TotalResultsCount"] not found.
	at org.json.JSONObject.get(JSONObject.java:498)
	at com.data.altisource.library.MptRefinanceTestLibrary.getAllFileCount(MptRefinanceTestLibrary.java:335)
	at com.data.altisource.library.MptRefinanceTestLibrary.refinanceAllDataInsertQueries(MptRefinanceTestLibrary.java:70)
	at com.data.altisource.library.MptRefinanceTestLibrary.refinanceAllDataCreation(MptRefinanceTestLibrary.java:202)
	at com.altisource.MPT_RefinanceTest.MptRefinanceTests.runMptRefinanceTitleNEscrowTest(MptRefinanceTests.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:715)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:907)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1237)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:51)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:85)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1197)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1122)
	at org.testng.TestNG.run(TestNG.java:1030)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- runMptRefinanceTitleNEscrowTest -->
  <testcase name="runMptRefinanceTitleNEscrowTest" time="30.134" classname="com.altisource.MPT_RefinanceTest.MptRefinanceTests">
    <failure type="org.json.JSONException" message="JSONObject[&quot;TotalResultsCount&quot;] not found.">
      <![CDATA[org.json.JSONException: JSONObject["TotalResultsCount"] not found.
	at org.json.JSONObject.get(JSONObject.java:498)
	at com.data.altisource.library.MptRefinanceTestLibrary.getAllFileCount(MptRefinanceTestLibrary.java:335)
	at com.data.altisource.library.MptRefinanceTestLibrary.refinanceAllDataInsertQueries(MptRefinanceTestLibrary.java:70)
	at com.data.altisource.library.MptRefinanceTestLibrary.refinanceAllDataCreation(MptRefinanceTestLibrary.java:202)
	at com.altisource.MPT_RefinanceTest.MptRefinanceTests.runMptRefinanceTitleNEscrowTest(MptRefinanceTests.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:715)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:907)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1237)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:51)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:85)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1197)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1122)
	at org.testng.TestNG.run(TestNG.java:1030)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- runMptRefinanceTitleNEscrowTest -->
  <testcase name="runMptRefinanceTitleNEscrowTest" time="23.517" classname="com.altisource.MPT_RefinanceTest.MptRefinanceTests">
    <failure type="org.json.JSONException" message="JSONObject[&quot;TotalResultsCount&quot;] not found.">
      <![CDATA[org.json.JSONException: JSONObject["TotalResultsCount"] not found.
	at org.json.JSONObject.get(JSONObject.java:498)
	at com.data.altisource.library.MptRefinanceTestLibrary.getAllFileCount(MptRefinanceTestLibrary.java:335)
	at com.data.altisource.library.MptRefinanceTestLibrary.refinanceAllDataInsertQueries(MptRefinanceTestLibrary.java:70)
	at com.data.altisource.library.MptRefinanceTestLibrary.refinanceAllDataCreation(MptRefinanceTestLibrary.java:202)
	at com.altisource.MPT_RefinanceTest.MptRefinanceTests.runMptRefinanceTitleNEscrowTest(MptRefinanceTests.java:38)
	at sun.reflect.GeneratedMethodAccessor137.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:715)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:907)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1237)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:51)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:85)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1197)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1122)
	at org.testng.TestNG.run(TestNG.java:1030)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- runMptRefinanceTitleNEscrowTest -->
  <testcase name="runMptRefinanceTitleNEscrowTest" time="28.596" classname="com.altisource.MPT_RefinanceTest.MptRefinanceTests">
    <failure type="org.json.JSONException" message="JSONObject[&quot;TotalResultsCount&quot;] not found.">
      <![CDATA[org.json.JSONException: JSONObject["TotalResultsCount"] not found.
	at org.json.JSONObject.get(JSONObject.java:498)
	at com.data.altisource.library.MptRefinanceTestLibrary.getAllFileCount(MptRefinanceTestLibrary.java:335)
	at com.data.altisource.library.MptRefinanceTestLibrary.refinanceAllDataInsertQueries(MptRefinanceTestLibrary.java:70)
	at com.data.altisource.library.MptRefinanceTestLibrary.refinanceAllDataCreation(MptRefinanceTestLibrary.java:202)
	at com.altisource.MPT_RefinanceTest.MptRefinanceTests.runMptRefinanceTitleNEscrowTest(MptRefinanceTests.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:715)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:907)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1237)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:51)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:85)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1197)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1122)
	at org.testng.TestNG.run(TestNG.java:1030)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- runMptRefinanceTitleNEscrowTest -->
  <testcase name="runMptRefinanceTitleNEscrowTest" time="31.750" classname="com.altisource.MPT_RefinanceTest.MptRefinanceTests">
    <failure type="org.json.JSONException" message="JSONObject[&quot;TotalResultsCount&quot;] not found.">
      <![CDATA[org.json.JSONException: JSONObject["TotalResultsCount"] not found.
	at org.json.JSONObject.get(JSONObject.java:498)
	at com.data.altisource.library.MptRefinanceTestLibrary.getAllFileCount(MptRefinanceTestLibrary.java:335)
	at com.data.altisource.library.MptRefinanceTestLibrary.refinanceAllDataInsertQueries(MptRefinanceTestLibrary.java:70)
	at com.data.altisource.library.MptRefinanceTestLibrary.refinanceAllDataCreation(MptRefinanceTestLibrary.java:202)
	at com.altisource.MPT_RefinanceTest.MptRefinanceTests.runMptRefinanceTitleNEscrowTest(MptRefinanceTests.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:715)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:907)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1237)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:51)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:85)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1197)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1122)
	at org.testng.TestNG.run(TestNG.java:1030)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- runMptRefinanceTitleNEscrowTest -->
  <testcase name="runMptRefinanceTitleNEscrowTest" time="31.089" classname="com.altisource.MPT_RefinanceTest.MptRefinanceTests">
    <failure type="org.json.JSONException" message="JSONObject[&quot;TotalResultsCount&quot;] not found.">
      <![CDATA[org.json.JSONException: JSONObject["TotalResultsCount"] not found.
	at org.json.JSONObject.get(JSONObject.java:498)
	at com.data.altisource.library.MptRefinanceTestLibrary.getAllFileCount(MptRefinanceTestLibrary.java:335)
	at com.data.altisource.library.MptRefinanceTestLibrary.refinanceAllDataInsertQueries(MptRefinanceTestLibrary.java:70)
	at com.data.altisource.library.MptRefinanceTestLibrary.refinanceAllDataCreation(MptRefinanceTestLibrary.java:202)
	at com.altisource.MPT_RefinanceTest.MptRefinanceTests.runMptRefinanceTitleNEscrowTest(MptRefinanceTests.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:715)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:907)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1237)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:51)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:85)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1197)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1122)
	at org.testng.TestNG.run(TestNG.java:1030)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- runMptRefinanceTitleNEscrowTest -->
  <testcase name="runMptRefinanceTitleNEscrowTest" time="22.925" classname="com.altisource.MPT_RefinanceTest.MptRefinanceTests">
    <failure type="org.json.JSONException" message="JSONObject[&quot;TotalResultsCount&quot;] not found.">
      <![CDATA[org.json.JSONException: JSONObject["TotalResultsCount"] not found.
	at org.json.JSONObject.get(JSONObject.java:498)
	at com.data.altisource.library.MptRefinanceTestLibrary.getAllFileCount(MptRefinanceTestLibrary.java:335)
	at com.data.altisource.library.MptRefinanceTestLibrary.refinanceAllDataInsertQueries(MptRefinanceTestLibrary.java:70)
	at com.data.altisource.library.MptRefinanceTestLibrary.refinanceAllDataCreation(MptRefinanceTestLibrary.java:202)
	at com.altisource.MPT_RefinanceTest.MptRefinanceTests.runMptRefinanceTitleNEscrowTest(MptRefinanceTests.java:38)
	at sun.reflect.GeneratedMethodAccessor137.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:715)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:907)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1237)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:51)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:85)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1197)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1122)
	at org.testng.TestNG.run(TestNG.java:1030)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- runMptRefinanceTitleNEscrowTest -->
  <testcase name="runMptRefinanceTitleNEscrowTest" time="30.569" classname="com.altisource.MPT_RefinanceTest.MptRefinanceTests">
    <failure type="org.json.JSONException" message="JSONObject[&quot;TotalResultsCount&quot;] not found.">
      <![CDATA[org.json.JSONException: JSONObject["TotalResultsCount"] not found.
	at org.json.JSONObject.get(JSONObject.java:498)
	at com.data.altisource.library.MptRefinanceTestLibrary.getAllFileCount(MptRefinanceTestLibrary.java:335)
	at com.data.altisource.library.MptRefinanceTestLibrary.refinanceAllDataInsertQueries(MptRefinanceTestLibrary.java:70)
	at com.data.altisource.library.MptRefinanceTestLibrary.refinanceAllDataCreation(MptRefinanceTestLibrary.java:202)
	at com.altisource.MPT_RefinanceTest.MptRefinanceTests.runMptRefinanceTitleNEscrowTest(MptRefinanceTests.java:38)
	at sun.reflect.GeneratedMethodAccessor137.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:715)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:907)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1237)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:51)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:85)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1197)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1122)
	at org.testng.TestNG.run(TestNG.java:1030)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- runMptRefinanceTitleNEscrowTest -->
  <testcase name="runMptRefinanceTitleNEscrowTest" time="27.831" classname="com.altisource.MPT_RefinanceTest.MptRefinanceTests">
    <failure type="org.json.JSONException" message="JSONObject[&quot;TotalResultsCount&quot;] not found.">
      <![CDATA[org.json.JSONException: JSONObject["TotalResultsCount"] not found.
	at org.json.JSONObject.get(JSONObject.java:498)
	at com.data.altisource.library.MptRefinanceTestLibrary.getAllFileCount(MptRefinanceTestLibrary.java:335)
	at com.data.altisource.library.MptRefinanceTestLibrary.refinanceAllDataInsertQueries(MptRefinanceTestLibrary.java:70)
	at com.data.altisource.library.MptRefinanceTestLibrary.refinanceAllDataCreation(MptRefinanceTestLibrary.java:202)
	at com.altisource.MPT_RefinanceTest.MptRefinanceTests.runMptRefinanceTitleNEscrowTest(MptRefinanceTests.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:715)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:907)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1237)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:51)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:85)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1197)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1122)
	at org.testng.TestNG.run(TestNG.java:1030)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- runMptRefinanceTitleNEscrowTest -->
  <testcase name="runMptRefinanceTitleNEscrowTest" time="29.983" classname="com.altisource.MPT_RefinanceTest.MptRefinanceTests">
    <failure type="org.json.JSONException" message="JSONObject[&quot;TotalResultsCount&quot;] not found.">
      <![CDATA[org.json.JSONException: JSONObject["TotalResultsCount"] not found.
	at org.json.JSONObject.get(JSONObject.java:498)
	at com.data.altisource.library.MptRefinanceTestLibrary.getAllFileCount(MptRefinanceTestLibrary.java:335)
	at com.data.altisource.library.MptRefinanceTestLibrary.refinanceAllDataInsertQueries(MptRefinanceTestLibrary.java:70)
	at com.data.altisource.library.MptRefinanceTestLibrary.refinanceAllDataCreation(MptRefinanceTestLibrary.java:202)
	at com.altisource.MPT_RefinanceTest.MptRefinanceTests.runMptRefinanceTitleNEscrowTest(MptRefinanceTests.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:715)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:907)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1237)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:51)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:85)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1197)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1122)
	at org.testng.TestNG.run(TestNG.java:1030)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- runMptRefinanceTitleNEscrowTest -->
  <testcase name="runMptRefinanceTitleNEscrowTest" time="23.666" classname="com.altisource.MPT_RefinanceTest.MptRefinanceTests">
    <failure type="org.json.JSONException" message="JSONObject[&quot;TotalResultsCount&quot;] not found.">
      <![CDATA[org.json.JSONException: JSONObject["TotalResultsCount"] not found.
	at org.json.JSONObject.get(JSONObject.java:498)
	at com.data.altisource.library.MptRefinanceTestLibrary.getAllFileCount(MptRefinanceTestLibrary.java:335)
	at com.data.altisource.library.MptRefinanceTestLibrary.refinanceAllDataInsertQueries(MptRefinanceTestLibrary.java:70)
	at com.data.altisource.library.MptRefinanceTestLibrary.refinanceAllDataCreation(MptRefinanceTestLibrary.java:202)
	at com.altisource.MPT_RefinanceTest.MptRefinanceTests.runMptRefinanceTitleNEscrowTest(MptRefinanceTests.java:38)
	at sun.reflect.GeneratedMethodAccessor137.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:715)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:907)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1237)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:51)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:85)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1197)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1122)
	at org.testng.TestNG.run(TestNG.java:1030)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- runMptRefinanceTitleNEscrowTest -->
  <testcase name="runMptRefinanceTitleNEscrowTest" time="37.366" classname="com.altisource.MPT_RefinanceTest.MptRefinanceTests">
    <failure type="org.json.JSONException" message="JSONObject[&quot;TotalResultsCount&quot;] not found.">
      <![CDATA[org.json.JSONException: JSONObject["TotalResultsCount"] not found.
	at org.json.JSONObject.get(JSONObject.java:498)
	at com.data.altisource.library.MptRefinanceTestLibrary.getAllFileCount(MptRefinanceTestLibrary.java:335)
	at com.data.altisource.library.MptRefinanceTestLibrary.refinanceAllDataInsertQueries(MptRefinanceTestLibrary.java:70)
	at com.data.altisource.library.MptRefinanceTestLibrary.refinanceAllDataCreation(MptRefinanceTestLibrary.java:202)
	at com.altisource.MPT_RefinanceTest.MptRefinanceTests.runMptRefinanceTitleNEscrowTest(MptRefinanceTests.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:715)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:907)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1237)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:51)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:85)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1197)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1122)
	at org.testng.TestNG.run(TestNG.java:1030)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- runMptRefinanceTitleNEscrowTest -->
  <testcase name="runMptRefinanceTitleNEscrowTest" time="20.279" classname="com.altisource.MPT_RefinanceTest.MptRefinanceTests">
    <failure type="java.lang.NumberFormatException" message="For input string: &quot;&quot;">
      <![CDATA[java.lang.NumberFormatException: For input string: ""
	at java.lang.NumberFormatException.forInputString(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at com.data.altisource.library.MptRefinanceTestLibrary.refinanceAllDataInsertQueries(MptRefinanceTestLibrary.java:65)
	at com.data.altisource.library.MptRefinanceTestLibrary.refinanceAllDataCreation(MptRefinanceTestLibrary.java:202)
	at com.altisource.MPT_RefinanceTest.MptRefinanceTests.runMptRefinanceTitleNEscrowTest(MptRefinanceTests.java:38)
	at sun.reflect.GeneratedMethodAccessor137.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:715)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:907)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1237)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:51)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:85)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1197)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1122)
	at org.testng.TestNG.run(TestNG.java:1030)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- runMptRefinanceTitleNEscrowTest -->
  <testcase name="runMptRefinanceTitleNEscrowTest" time="21.541" classname="com.altisource.MPT_RefinanceTest.MptRefinanceTests">
    <failure type="java.lang.NumberFormatException" message="null">
      <![CDATA[java.lang.NumberFormatException: null
	at java.lang.Integer.parseInt(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at com.data.altisource.library.MptRefinanceTestLibrary.getMPTInternalChartAPI(MptRefinanceTestLibrary.java:264)
	at com.data.altisource.library.MptRefinanceTestLibrary.refinanceAllDataInsertQueries(MptRefinanceTestLibrary.java:69)
	at com.data.altisource.library.MptRefinanceTestLibrary.refinanceAllDataCreation(MptRefinanceTestLibrary.java:202)
	at com.altisource.MPT_RefinanceTest.MptRefinanceTests.runMptRefinanceTitleNEscrowTest(MptRefinanceTests.java:38)
	at sun.reflect.GeneratedMethodAccessor137.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:715)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:907)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1237)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:51)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:85)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1197)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1122)
	at org.testng.TestNG.run(TestNG.java:1030)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- runMptRefinanceTitleNEscrowTest -->
  <testcase name="runMptRefinanceTitleNEscrowTest" time="20.348" classname="com.altisource.MPT_RefinanceTest.MptRefinanceTests">
    <failure type="java.lang.NumberFormatException" message="For input string: &quot;&quot;">
      <![CDATA[java.lang.NumberFormatException: For input string: ""
	at java.lang.NumberFormatException.forInputString(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at com.data.altisource.library.MptRefinanceTestLibrary.refinanceAllDataInsertQueries(MptRefinanceTestLibrary.java:65)
	at com.data.altisource.library.MptRefinanceTestLibrary.refinanceAllDataCreation(MptRefinanceTestLibrary.java:202)
	at com.altisource.MPT_RefinanceTest.MptRefinanceTests.runMptRefinanceTitleNEscrowTest(MptRefinanceTests.java:38)
	at sun.reflect.GeneratedMethodAccessor137.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:715)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:907)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1237)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:51)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:85)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1197)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1122)
	at org.testng.TestNG.run(TestNG.java:1030)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- runMptRefinanceTitleNEscrowTest -->
  <testcase name="runMptRefinanceTitleNEscrowTest" time="28.985" classname="com.altisource.MPT_RefinanceTest.MptRefinanceTests">
    <failure type="org.json.JSONException" message="JSONObject[&quot;TotalResultsCount&quot;] not found.">
      <![CDATA[org.json.JSONException: JSONObject["TotalResultsCount"] not found.
	at org.json.JSONObject.get(JSONObject.java:498)
	at com.data.altisource.library.MptRefinanceTestLibrary.getAllFileCount(MptRefinanceTestLibrary.java:335)
	at com.data.altisource.library.MptRefinanceTestLibrary.refinanceAllDataInsertQueries(MptRefinanceTestLibrary.java:70)
	at com.data.altisource.library.MptRefinanceTestLibrary.refinanceAllDataCreation(MptRefinanceTestLibrary.java:202)
	at com.altisource.MPT_RefinanceTest.MptRefinanceTests.runMptRefinanceTitleNEscrowTest(MptRefinanceTests.java:38)
	at sun.reflect.GeneratedMethodAccessor137.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:715)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:907)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1237)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:51)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:85)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1197)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1122)
	at org.testng.TestNG.run(TestNG.java:1030)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- runMptRefinanceTitleNEscrowTest -->
  <testcase name="runMptRefinanceTitleNEscrowTest" time="33.822" classname="com.altisource.MPT_RefinanceTest.MptRefinanceTests">
    <failure type="org.json.JSONException" message="JSONObject[&quot;TotalResultsCount&quot;] not found.">
      <![CDATA[org.json.JSONException: JSONObject["TotalResultsCount"] not found.
	at org.json.JSONObject.get(JSONObject.java:498)
	at com.data.altisource.library.MptRefinanceTestLibrary.getAllFileCount(MptRefinanceTestLibrary.java:335)
	at com.data.altisource.library.MptRefinanceTestLibrary.refinanceAllDataInsertQueries(MptRefinanceTestLibrary.java:70)
	at com.data.altisource.library.MptRefinanceTestLibrary.refinanceAllDataCreation(MptRefinanceTestLibrary.java:202)
	at com.altisource.MPT_RefinanceTest.MptRefinanceTests.runMptRefinanceTitleNEscrowTest(MptRefinanceTests.java:38)
	at sun.reflect.GeneratedMethodAccessor137.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:715)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:907)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1237)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:51)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:85)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1197)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1122)
	at org.testng.TestNG.run(TestNG.java:1030)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- runMptRefinanceTitleNEscrowTest -->
  <testcase name="runMptRefinanceTitleNEscrowTest" time="23.461" classname="com.altisource.MPT_RefinanceTest.MptRefinanceTests">
    <failure type="org.json.JSONException" message="JSONObject[&quot;TotalResultsCount&quot;] not found.">
      <![CDATA[org.json.JSONException: JSONObject["TotalResultsCount"] not found.
	at org.json.JSONObject.get(JSONObject.java:498)
	at com.data.altisource.library.MptRefinanceTestLibrary.getAllFileCount(MptRefinanceTestLibrary.java:335)
	at com.data.altisource.library.MptRefinanceTestLibrary.refinanceAllDataInsertQueries(MptRefinanceTestLibrary.java:70)
	at com.data.altisource.library.MptRefinanceTestLibrary.refinanceAllDataCreation(MptRefinanceTestLibrary.java:202)
	at com.altisource.MPT_RefinanceTest.MptRefinanceTests.runMptRefinanceTitleNEscrowTest(MptRefinanceTests.java:38)
	at sun.reflect.GeneratedMethodAccessor137.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:715)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:907)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1237)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:51)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:85)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1197)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1122)
	at org.testng.TestNG.run(TestNG.java:1030)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- runMptRefinanceTitleNEscrowTest -->
  <testcase name="runMptRefinanceTitleNEscrowTest" time="23.638" classname="com.altisource.MPT_RefinanceTest.MptRefinanceTests">
    <failure type="org.json.JSONException" message="JSONObject[&quot;TotalResultsCount&quot;] not found.">
      <![CDATA[org.json.JSONException: JSONObject["TotalResultsCount"] not found.
	at org.json.JSONObject.get(JSONObject.java:498)
	at com.data.altisource.library.MptRefinanceTestLibrary.getAllFileCount(MptRefinanceTestLibrary.java:335)
	at com.data.altisource.library.MptRefinanceTestLibrary.refinanceAllDataInsertQueries(MptRefinanceTestLibrary.java:70)
	at com.data.altisource.library.MptRefinanceTestLibrary.refinanceAllDataCreation(MptRefinanceTestLibrary.java:202)
	at com.altisource.MPT_RefinanceTest.MptRefinanceTests.runMptRefinanceTitleNEscrowTest(MptRefinanceTests.java:38)
	at sun.reflect.GeneratedMethodAccessor137.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:715)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:907)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1237)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:51)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:85)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1197)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1122)
	at org.testng.TestNG.run(TestNG.java:1030)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- runMptRefinanceTitleNEscrowTest -->
  <testcase name="runMptRefinanceTitleNEscrowTest" time="29.426" classname="com.altisource.MPT_RefinanceTest.MptRefinanceTests">
    <failure type="org.json.JSONException" message="JSONObject[&quot;TotalResultsCount&quot;] not found.">
      <![CDATA[org.json.JSONException: JSONObject["TotalResultsCount"] not found.
	at org.json.JSONObject.get(JSONObject.java:498)
	at com.data.altisource.library.MptRefinanceTestLibrary.getAllFileCount(MptRefinanceTestLibrary.java:335)
	at com.data.altisource.library.MptRefinanceTestLibrary.refinanceAllDataInsertQueries(MptRefinanceTestLibrary.java:70)
	at com.data.altisource.library.MptRefinanceTestLibrary.refinanceAllDataCreation(MptRefinanceTestLibrary.java:202)
	at com.altisource.MPT_RefinanceTest.MptRefinanceTests.runMptRefinanceTitleNEscrowTest(MptRefinanceTests.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:715)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:907)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1237)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:51)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:85)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1197)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1122)
	at org.testng.TestNG.run(TestNG.java:1030)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- runMptRefinanceTitleNEscrowTest -->
  <testcase name="runMptRefinanceTitleNEscrowTest" time="23.218" classname="com.altisource.MPT_RefinanceTest.MptRefinanceTests">
    <failure type="org.json.JSONException" message="JSONObject[&quot;TotalResultsCount&quot;] not found.">
      <![CDATA[org.json.JSONException: JSONObject["TotalResultsCount"] not found.
	at org.json.JSONObject.get(JSONObject.java:498)
	at com.data.altisource.library.MptRefinanceTestLibrary.getAllFileCount(MptRefinanceTestLibrary.java:335)
	at com.data.altisource.library.MptRefinanceTestLibrary.refinanceAllDataInsertQueries(MptRefinanceTestLibrary.java:70)
	at com.data.altisource.library.MptRefinanceTestLibrary.refinanceAllDataCreation(MptRefinanceTestLibrary.java:202)
	at com.altisource.MPT_RefinanceTest.MptRefinanceTests.runMptRefinanceTitleNEscrowTest(MptRefinanceTests.java:38)
	at sun.reflect.GeneratedMethodAccessor137.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:715)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:907)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1237)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:51)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:85)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1197)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1122)
	at org.testng.TestNG.run(TestNG.java:1030)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- runMptRefinanceTitleNEscrowTest -->
  <testcase name="runMptRefinanceTitleNEscrowTest" time="28.425" classname="com.altisource.MPT_RefinanceTest.MptRefinanceTests">
    <failure type="org.json.JSONException" message="JSONObject[&quot;TotalResultsCount&quot;] not found.">
      <![CDATA[org.json.JSONException: JSONObject["TotalResultsCount"] not found.
	at org.json.JSONObject.get(JSONObject.java:498)
	at com.data.altisource.library.MptRefinanceTestLibrary.getAllFileCount(MptRefinanceTestLibrary.java:335)
	at com.data.altisource.library.MptRefinanceTestLibrary.refinanceAllDataInsertQueries(MptRefinanceTestLibrary.java:70)
	at com.data.altisource.library.MptRefinanceTestLibrary.refinanceAllDataCreation(MptRefinanceTestLibrary.java:202)
	at com.altisource.MPT_RefinanceTest.MptRefinanceTests.runMptRefinanceTitleNEscrowTest(MptRefinanceTests.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:715)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:907)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1237)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:51)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:85)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1197)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1122)
	at org.testng.TestNG.run(TestNG.java:1030)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- runMptRefinanceTitleNEscrowTest -->
</testsuite> <!-- com.altisource.MPT_RefinanceTest.MptRefinanceTests -->
